# Generated by Django 2.1.3 on 2018-11-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('narrative', models.TextField()),
                ('issuing_department', models.CharField(max_length=50)),
                ('associated_filename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issue', models.DateField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('public_address', models.CharField(max_length=250)),
                ('nonce', models.CharField(default=None, max_length=50)),
                ('add_issuer_timestamp', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PersonIssuances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issued', models.BooleanField()),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Person')),
            ],
        ),
    ]
