# Generated by Django 2.1.3 on 2018-11-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('issuing_department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issue', models.DateField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('otc', models.CharField(max_length=50, unique=True)),
                ('blockchain_address', models.CharField(max_length=50, unique=True)),
                ('add_issuer_timestamp', models.DateTimeField()),
                ('issuances', models.ManyToManyField(to='issuer.Issuance')),
            ],
        ),
    ]
