# Generated by Django 2.1.3 on 2018-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='issuances',
            field=models.ManyToManyField(default=None, to='issuer.Issuance'),
        ),
    ]
