# Generated by Django 2.2.3 on 2019-07-02 16:40

from django.db import migrations, models
import issuer.models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='badge_id',
            field=models.TextField(default=issuer.models.get_uuid),
        ),
        migrations.AddField(
            model_name='issuance',
            name='url_id',
            field=models.TextField(default=''),
        ),
    ]
