# Generated by Django 2.1.3 on 2018-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='add_issuer_timestamp',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='nonce',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='public_address',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
