# Generated by Django 2.2.3 on 2019-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0002_auto_20190702_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='people',
            field=models.ManyToManyField(related_name='issuances', through='issuer.PersonIssuances', to='issuer.Person'),
        ),
    ]
