# Generated by Django 2.2.3 on 2019-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0003_issuance_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='people',
            field=models.ManyToManyField(related_name='issuance', through='issuer.PersonIssuances', to='issuer.Person'),
        ),
    ]
