# Generated by Django 2.2.4 on 2019-08-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_auto_20190805_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certmailerconfig',
            name='config',
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='cert_email_body',
            field=models.TextField(default='<p>Dear $first_name</p><p>We would like to recognize your achievement with a Blockcerts digital credential. You can import your Blockcert in two ways:</p><ul><li>If you’re reading this email on your mobile device, <a clicktracking="off" href="$cert_url">Click this link to add your credential to your Blockcerts wallet</a>.</li><li>If you’re reading this email on your desktop, scan the QR code below using your mobile device.</li></ul>$qrcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='cert_email_subject',
            field=models.CharField(default='We have issued you a Blockcert', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='from_email',
            field=models.CharField(default='noreply@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='introduction_email_body',
            field=models.TextField(default='<p>Dear $first_name</p><p>In order to issue you a blockchain certificate you need to register your wallet with our issuer. Here\'s how to do that:</p><p><b>Step 1: Install the app</b></p><p>Install the “Blockcerts Wallet” app on your phone (available on the iOS or Android app stores).</p><br><p><b>Step 2: Add issuer</b></p><p>There are two ways to add us as an issuer:</p><ul><li>If you’re reading this email on your mobile device, <a clicktracking="off" href="$introduction_url">Click this link to add us as an issuer</a>.</li><li>If you’re reading this email on your desktop, scan the QR code below using your mobile device.</li></ul>$qrcode<p>Please note: it’s important to complete these steps in this order. After you have added us as an issuer, you will be notified when your credential is ready.</p>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='introduction_email_subject',
            field=models.CharField(default='Add us as a Blockcerts issuer', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='mailer',
            field=models.CharField(default='stdout', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='cert_mailer_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issuer.CertMailerConfig'),
            preserve_default=False,
        ),
    ]
