# Generated by Django 2.1.3 on 2018-11-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0005_auto_20181124_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='add_issuer_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
