# Generated by Django 2.2.4 on 2019-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0005_auto_20190815_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certmailerconfig',
            name='mailer',
            field=models.CharField(choices=[('stdout', 'Log instead of mailing'), ('mandrill', 'Mailchimp Mandrill'), ('sendgrid', 'Sendgrid')], max_length=50),
        ),
    ]
