# Generated by Django 2.2.4 on 2019-08-20 13:41

from django.db import migrations, models


def nullEmptyNonces(apps, schema_editor):
    Person = apps.get_model('issuer', 'Person')
    for row in Person.objects.filter(nonce=''):
        row.nonce = None
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0006_auto_20190815_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nonce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(nullEmptyNonces),
        migrations.AlterField(
            model_name='person',
            name='nonce',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True)
        )
    ]
