# Generated by Django 2.2.5 on 2019-09-10 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0007_nullablenonces'),
    ]

    operations = [
        migrations.AddField(
            model_name='personissuances',
            name='last_reminded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
