# Generated by Django 2.1.5 on 2019-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0008_auto_20181126_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertMailerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField()),
            ],
        ),
    ]
