# Generated by Django 2.2.5 on 2019-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0009_personissuances_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='personissuances',
            options={'ordering': ('person__last_name',)},
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
