# Generated by Django 2.1.3 on 2019-03-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0009_certmailerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertToolsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField()),
            ],
        ),
    ]
