# Generated by Django 2.2.5 on 2019-09-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0010_auto_20190912_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='certificate_template',
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='display_html_template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='issuer_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='issuer_id',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='issuer_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='issuer_public_key',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='issuer_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certtoolsconfig',
            name='revocation_list',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='cert_tools_config',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='issuer.CertToolsConfig'),
        ),
    ]
