# Generated by Django 2.1.3 on 2019-03-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0010_certtoolsconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuance',
            name='associated_filename',
        ),
        migrations.AddField(
            model_name='issuance',
            name='certificate_template',
            field=models.TextField(default=''),
        ),
    ]
