# Generated by Django 2.2.5 on 2019-09-17 12:58

from django.db import migrations
import json


def forwards(apps, schema_editor):
    configs = apps.get_model('issuer', 'CertToolsConfig')
    for config in configs.objects.all():
        content = json.loads(config.config)
        config.issuer_url = content['issuer_url']
        config.issuer_email = content['issuer_email']
        config.issuer_name = content['issuer_name']
        config.issuer_id = content['issuer_id']
        config.revocation_list = content['revocation_list']
        config.issuer_public_key = content['issuer_public_key']
        config.display_html_template = content['additional_global_fields'][0]['value']
        config.save()
    default = configs.objects.first()
    for cred in apps.get_model('issuer', 'Credential').objects.all():
        cred.cert_tools_config = default
        cred.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0011_cert_tools_config'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
