# Generated by Django 2.2.5 on 2019-09-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0012_cert_tools_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certtoolsconfig',
            name='config',
        ),
        migrations.AlterField(
            model_name='credential',
            name='cert_tools_config',
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='issuer.CertToolsConfig',
            ),
        ),
    ]
