# Generated by Django 2.2.5 on 2019-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0013_cert_tools_config_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='certmailerconfig',
            name='remind_email_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certmailerconfig',
            name='remind_email_subject',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
