# Generated by Django 2.2.6 on 2019-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0015_issuance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personissuances',
            name='cert_uid',
            field=models.TextField(default=''),
        ),
    ]
