# Generated by Django 2.2.6 on 2019-10-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0016_personissuances_cert_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personissuances',
            name='unsigned_certificate',
        ),
    ]
