# Generated by Django 2.2.7 on 2019-11-11 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0017_remove_personissuances_unsigned_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personissuances',
            name='approved_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personissuances',
            name='issued_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
