# Generated by Django 2.2.6 on 2019-11-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0018_auto_20191111_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='certtoolsconfig',
            name='issuer_api_url',
            field=models.URLField(default='http://cert-issuer/cert_issuer/api/v1.0/issue'),
            preserve_default=False,
        ),
    ]
