# Generated by Django 2.2.8 on 2019-12-11 01:29

from django.db import migrations, models
import django.db.models.deletion

def link_groups(apps, schema_editor):
    Credential = apps.get_model('issuer', 'Credential')
    Group = apps.get_model('auth', 'Group')
    for credential in Credential.objects.all():
        group, created = Group.objects.get_or_create(name=credential.issuing_department)
        credential.issuing_department_link = group
        credential.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('issuer', '0019_certtoolsconfig_issuer_api_url'),
    ]
    operations = [
        migrations.AddField(
            model_name='credential',
            name='issuing_department_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.RunPython(link_groups),
        migrations.RemoveField(
            model_name='credential',
            name='issuing_department'
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='issuing_department_link',
            new_name='issuing_department'
        ),
    ]

